### ISSUE TITLE
Develop sign up screen functionality

### ISSUE THREAD

**Issue by BrandonVG** [BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda#3]
## REQUIREMENTS / DESCRIPTION

```[tasklist]
### Tasks
- [ ] Use useState hook to add functionality to fields
- [ ] Use the database connection to let the application save new users
- [ ] Create the session
- [ ] Add validation to email field
- [ ] Add validation to name field
- [ ] Add validation to password field
```
