### ISSUE TITLE
Add validation to sign up

### ISSUE THREAD

**Issue by BrandonVG** [BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda#4]
## REQUIREMENTS / DESCRIPTION

```[tasklist]
### Tasks
- [ ] Add validation to email field
- [ ] Add validation to name field
- [ ] Add validation to password field
- [ ] Add validation to have checked the terms and privacy policy
```
