### ISSUE TITLE
Log in functionality with firebase

### ISSUE THREAD

**Issue by BrandonVG** [BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda#6]
## REQUIREMENTS / DESCRIPTION

```[tasklist]
### Tasks
- [ ] Connection to firebase to get the user by email and password
- [ ] Connection to firebase to get the user by google account
- [ ] The log in screen should validate the fields to add security to the app
- [ ] Add navigation to redirect when sign in or login
- [ ] Create a sign out button to end a session that is available on the screen after login/signup
- [ ] Redirect to log in screen after logout
```
